name: Development workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Development Code
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npm run build --if-present
        env:
          CI: false
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: "8a286e0a-e50b-4ed1-8047-a6e778c3d87b"
          heroku_app_name: 'e-posyandu-web'
          heroku_email: "asepbudiyana12@gmail.com"